import {useEffect,useState} from 'react';
import './review.css';
const scores=[['Brand Identity',90],['Social Presence',82],['Market Position',80],['Revenue Potential',84],['Customer Trust',75],['Customer Experience',58],['Scalability',55],['Website Experience',45],['Business Systems',40]];
const success=[['More Families','A professional first impression creates greater confidence and more registrations.'],['Stronger Parent Relationships','Parents stay informed without searching through texts or wondering what comes next.'],['More Athlete Development','Players remain connected to their progress long after practice ends.'],['Greater Recruiting Opportunities','Every athlete has a professional profile ready to share with college coaches.'],['More Time Coaching','Less administration means more time doing the work only you can do.'],['A Business Built for Growth','The organization becomes easier to manage, easier to grow, and easier for families to experience.']];
const Logo=({type})=><img className={`review-logo ${type}`} src={`/review/${type==='client'?'ftfb-logo':'ea-logo'}.png`} alt={type==='client'?'Form to Finish Basketball':'Efficiency Architects'}/>;
function Review(){const[progress,setProgress]=useState(0);useEffect(()=>{const fn=()=>setProgress(scrollY/(document.documentElement.scrollHeight-innerHeight)*100);addEventListener('scroll',fn);return()=>removeEventListener('scroll',fn)},[]);return <main className="review">
<div className="reading-progress" style={{width:`${progress}%`}}/><nav className="review-nav"><a href="#cover"><Logo type="consultant"/></a><div><a href="#assessment">Assessment</a><a href="#experience">Experience</a><a href="#roadmap">Roadmap</a><a href="#future">Future</a></div><span>CONFIDENTIAL</span></nav>
<section id="cover" className="r-cover"><div className="cover-copy"><div className="cover-brands"><Logo type="consultant"/><div><small>PREPARED BY</small><b>Efficiency Architects™</b></div></div><p className="kicker">STRATEGIC GROWTH REVIEW · VERSION 2.0</p><h1>Build the business<br/>you have already earned.</h1><p className="intro">A clearer path to more coaching, stronger family experiences, and sustainable growth.</p><div className="prepared"><span>Prepared exclusively for</span><strong>Dylan Debono</strong><small>Founder · Form to Finish Basketball</small></div></div><div className="cover-image"><img src="/review/dylan-debono-coaching-clean.png" alt="Dylan Debono coaching athletes"/></div></section>
<section className="chapter summary"><p className="kicker">EXECUTIVE SUMMARY</p><h2>The coaching experience is already strong.<br/>The business now needs to support it.</h2><div className="summary-grid"><p>Form to Finish Basketball has earned something systems cannot manufacture: the trust of families, a respected coaching reputation, and a clear commitment to athlete development.</p><p>The next stage is not about changing what happens on the court. It is about making every experience around the court feel just as organized, professional, and intentional.</p></div><div className="findings">{[['What is working','Coaching quality, authentic relationships, community trust, and athlete development.'],['What is getting harder','Scheduling, payments, communication, registration, and recruiting all require Dylan’s direct attention.'],['What changes next','The business begins carrying the administrative load so Dylan can spend more time coaching and leading.']].map((x,i)=><article key={x[0]}><span>0{i+1}</span><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></section>
<section id="assessment" className="chapter score-section"><p className="kicker">BUSINESS HEALTH ASSESSMENT</p><h2>The coaching is ahead of the business.</h2><div className="score-layout"><div className="score-grid">{scores.map(([n,s])=><article key={n}><span>{n}</span><b>{s}</b><i style={{width:`${s}%`}}/></article>)}</div><div className="hero-scores"><article><span>Overall Business Health</span><b>73</b></article><article><span>Transformation Opportunity</span><b>91</b></article></div></div><div className="numbers"><h3>What These Numbers Tell Us</h3><p>Every successful organization develops unevenly. Form to Finish Basketball has done the hardest part first. It has earned the trust of families through exceptional coaching, authentic relationships, and consistent player development. An Overall Business Health score of <b>73</b> confirms meaningful momentum. The Transformation Opportunity score of <b>91</b> tells the more important story.</p><strong>The greatest opportunity is not becoming a better basketball program. It is building a business that fully supports the program that already exists.</strong></div></section>
<section className="photo-story"><img src="/review/family-trust.png" alt="Coach speaking with a parent and athlete after practice"/><div><p className="kicker">THE EXPERIENCE FAMILIES REMEMBER</p><h2>Trust should continue long after practice ends.</h2><p>Families should never have to search through messages or wait for a reply to understand what comes next. Clear schedules, payments, updates, and progress create confidence before the first practice and strengthen relationships throughout the season.</p></div></section>
<section className="chapter capacity"><p className="kicker">CAPACITY LEAKS™</p><h2>The work surrounding coaching is taking time away from coaching.</h2><p className="wide">A Capacity Leak™ is work that requires Dylan’s attention even though a clear process could handle it more consistently.</p><div className="capacity-grid">{[['Scheduling','Repeated coordination','A calendar families can trust'],['Payments','Follow-up and reconciliation','Simple online payment records'],['Communication','The same questions answered repeatedly','One place for updates'],['Attendance','Informal tracking','Clear participation history'],['Recruiting','Follow-up held in memory','An organized recruiting pipeline'],['Registration','Manual enrollment steps','A guided online journey']].map(x=><article key={x[0]}><h3>{x[0]}</h3><small>TODAY</small><p>{x[1]}</p><small>TOMORROW</small><b>{x[2]}</b></article>)}</div></section>
<section id="experience" className="screens"><div className="screen-copy"><p className="kicker">THE FIRST IMPRESSION YOUR PROGRAM HAS EARNED</p><h2>Families understand the value before they ever send a message.</h2><p>The website becomes your hardest-working assistant, helping families discover the program, understand the philosophy, register, pay, and begin with confidence while you are coaching.</p></div><img src="/review/dylan-debono-coaching-clean.png" alt="Dylan Debono coaching athletes"/></section>
<section className="screens portal"><img src="/review/portal.png" alt="Proposed parent and athlete portal"/><div className="screen-copy"><p className="kicker">STAY CONNECTED</p><h2>Every family knows what happens next.</h2><p>Parents see schedules, payments, announcements, and coach updates. Athletes see development progress, feedback, milestones, and recruiting opportunities.</p><strong>Everything important is already waiting for them.</strong></div></section>
<section className="photo-story reverse"><img src="/review/athlete-reflection.png" alt="Athlete reviewing coach feedback after practice"/><div><p className="kicker">ATHLETE DEVELOPMENT</p><h2>Progress becomes something athletes can see and own.</h2><p>Feedback does not disappear when practice ends. Athletes stay connected to what they are learning, understand what comes next, and recognize the progress that consistent work creates.</p></div></section>
<section className="photo-story"><img src="/review/recruiting.png" alt="Basketball athlete being evaluated by college coaches"/><div><p className="kicker">RECRUITING OPPORTUNITY</p><h2>Earned attention becomes organized opportunity.</h2><p>Every athlete has a professional profile ready to share. Film, progress, conversations, and follow-up live in one clear recruiting process instead of being scattered across messages and memory.</p></div></section>
<section id="roadmap" className="chapter roadmap"><p className="kicker">90-DAY GROWTH ROADMAP</p><h2>Build the foundation without interrupting the coaching.</h2><div>{[['Days 1–30','Create clarity',['Confirm the family journey','Organize programs and pricing','Define registration and payment flow']],['Days 31–60','Connect the experience',['Launch the website','Centralize schedules and updates','Introduce parent and athlete access']],['Days 61–90','Build for growth',['Organize recruiting follow-up','Track athlete development','Create leadership visibility']]].map((p,i)=><article key={p[0]}><span>0{i+1}</span><small>{p[0]}</small><h3>{p[1]}</h3><ul>{p[2].map(x=><li key={x}>{x}</li>)}</ul></article>)}</div></section>
<section id="future" className="future-photo"><div className="dylan-face"><img src="/review/dylan-debono-coaching-clean.png" alt="Dylan Debono actively coaching athletes"/></div><div className="future-copy"><p className="kicker">THE FUTURE YOU’VE ALREADY EARNED</p><h2>Imagine walking into the gym knowing the business is already running.</h2><p>New families registered online before you arrived. Parents already know the schedule. Payments have already been received. Athletes are reviewing coach feedback and tracking their progress. Recruiters are viewing professional player profiles instead of searching through messages.</p><strong>Instead of spending your evening answering questions, you are spending it coaching, teaching, and helping young athletes grow.</strong></div></section>
<section className="chapter success"><p className="kicker">WHAT SUCCESS LOOKS LIKE</p><h2>The future of the business finally matches the quality of the coaching.</h2><div>{success.map((x,i)=><article key={x[0]}><span>0{i+1}</span><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div><p className="reflection">The systems themselves are not the destination. They create the time, consistency, and confidence that allow great organizations to keep doing what they do best. Form to Finish Basketball has already built something worth believing in. Now it is time to build the business around it.</p></section>
<footer className="review-footer"><Logo type="consultant"/><p>Every athlete deserves a great coach.<br/><b>Every great coach deserves a great organization.</b></p><small>Every mission deserves an organization designed around it.</small></footer>
</main>}
export default Review;
